### ISSUE TITLE
[GW2] Pact Supply tracking

### ISSUE THREAD

**Issue by Maselkov** [Maselkov/Maselkov-Cogs#10]

**Comment by n1tr0-5urf3r** [comment]
Looks like the API does not provide information about that 
We might get it from https://wiki.guildwars2.com/wiki/Pact_Supply_Network_Agent 
html code looks like this:
```
<td title="1"> 2017 Mar 24
</td>
<td> <a href="/wiki/Repair_Station" title="Repair Station">Repair Station</a></td>
<td><a href="/wiki/Pearl_Islet_Waypoint" title="Pearl Islet Waypoint" class="mw-redirect">Pearl Islet Waypoint</a></td>
<td><a href="/wiki/Breth_Ayahusasca" title="Breth Ayahusasca">Breth Ayahusasca</a></td>
<td><a href="/wiki/Shelter_Docks" title="Shelter Docks">Shelter Docks</a></td>
<td><a href="/wiki/Dolyak_Pass_Waypoint" title="Dolyak Pass Waypoint" class="mw-redirect">Dolyak Pass Waypoint</a></td>
<td><a href="/wiki/Hawkgates_Waypoint" title="Hawkgates Waypoint" class="mw-redirect">Hawkgates Waypoint</a>
```

I suggest downloading wiki page, search for today's date, get data from date's line + 7 following lines, output Title of Waypoint for each area in embed, maybe including Chatcode for WP, because full URL would be too long

**Comment by Maselkov** [comment]
I was just thinking of storing the rotation in a .json or the db I'm working on, since it seems to be static.

Also sorry for late reply, it missed my eyes

**Comment by Maselkov** [comment]
Added to mongo branch
