### ISSUE TITLE
Guild information

### ISSUE THREAD

**Issue by n1tr0-5urf3r** [Maselkov/Maselkov-Cogs#17]
I added guild commands (only general information, because i have nowhere guild leader access) to my fork. 
How can I merge it to yours?

**Comment by StephanMa** [comment]
You need to make a so called „Pull Request“ :)
The dev can decide if he wants to merge it or not

 

Von: n1tr0-5urf3r [mailto:notifications@github.com] 
Gesendet: Mittwoch, 22. März 2017 11:44
An: Maselkov/Maselkov-Cogs <Maselkov-Cogs@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Maselkov/Maselkov-Cogs] Guild information (#17)

 

I added guild commands (only general information, because i have nowhere guild leader access) to my fork.
How can I merge it to yours?

**Comment by n1tr0-5urf3r** [comment]
Allright thanks, I created one!

**Comment by Maselkov** [comment]
#18

**Comment by StephanMa** [comment]
Sadly i am not able to retrieve any Infos of our guild.

`&guild info` does not recognize the guild name, tag or key, which was previously retrieved by `&guild id [Name]`

**Comment by n1tr0-5urf3r** [comment]
You should not even need to get the ID via `&guild id [name]`, have you tried to just use `&guild info name`?

**Comment by StephanMa** [comment]
`&guild info "Make Love Not War"` returns ` API has responded with the following error: no such guild`

**Comment by StephanMa** [comment]
same without `"`

**Comment by StephanMa** [comment]
hmm.... nevermind... it seems to work... after some tries....

**Comment by n1tr0-5urf3r** [comment]
Nice to hear! Maybe it was a typo? Capital letters don't seem to matter
